# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import accommodation_search_pb2 as accommodation__search__pb2


class AccommodationSearchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAccommodation = channel.unary_unary(
                '/grpc_accommodation_search.AccommodationSearch/CreateAccommodation',
                request_serializer=accommodation__search__pb2.AccommodationDTO.SerializeToString,
                response_deserializer=accommodation__search__pb2.CreateAccommodationResponse.FromString,
                )
        self.CreatePriceInterval = channel.unary_unary(
                '/grpc_accommodation_search.AccommodationSearch/CreatePriceInterval',
                request_serializer=accommodation__search__pb2.CreatePriceIntervalRequest.SerializeToString,
                response_deserializer=accommodation__search__pb2.CreatePriceIntervalResponse.FromString,
                )
        self.CreateReservation = channel.unary_unary(
                '/grpc_accommodation_search.AccommodationSearch/CreateReservation',
                request_serializer=accommodation__search__pb2.CreateReservationRequest.SerializeToString,
                response_deserializer=accommodation__search__pb2.CreateReservationResponse.FromString,
                )
        self.DeleteReservation = channel.unary_unary(
                '/grpc_accommodation_search.AccommodationSearch/DeleteReservation',
                request_serializer=accommodation__search__pb2.DeleteReservationRequest.SerializeToString,
                response_deserializer=accommodation__search__pb2.DeleteReservationResponse.FromString,
                )
        self.DeleteHostsAccommodations = channel.unary_unary(
                '/grpc_accommodation_search.AccommodationSearch/DeleteHostsAccommodations',
                request_serializer=accommodation__search__pb2.DeleteHostsAccommodationsRequest.SerializeToString,
                response_deserializer=accommodation__search__pb2.DeleteHostsAccommodationsResponse.FromString,
                )


class AccommodationSearchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAccommodation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePriceInterval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteHostsAccommodations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccommodationSearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAccommodation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccommodation,
                    request_deserializer=accommodation__search__pb2.AccommodationDTO.FromString,
                    response_serializer=accommodation__search__pb2.CreateAccommodationResponse.SerializeToString,
            ),
            'CreatePriceInterval': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePriceInterval,
                    request_deserializer=accommodation__search__pb2.CreatePriceIntervalRequest.FromString,
                    response_serializer=accommodation__search__pb2.CreatePriceIntervalResponse.SerializeToString,
            ),
            'CreateReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateReservation,
                    request_deserializer=accommodation__search__pb2.CreateReservationRequest.FromString,
                    response_serializer=accommodation__search__pb2.CreateReservationResponse.SerializeToString,
            ),
            'DeleteReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteReservation,
                    request_deserializer=accommodation__search__pb2.DeleteReservationRequest.FromString,
                    response_serializer=accommodation__search__pb2.DeleteReservationResponse.SerializeToString,
            ),
            'DeleteHostsAccommodations': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteHostsAccommodations,
                    request_deserializer=accommodation__search__pb2.DeleteHostsAccommodationsRequest.FromString,
                    response_serializer=accommodation__search__pb2.DeleteHostsAccommodationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_accommodation_search.AccommodationSearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AccommodationSearch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAccommodation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_accommodation_search.AccommodationSearch/CreateAccommodation',
            accommodation__search__pb2.AccommodationDTO.SerializeToString,
            accommodation__search__pb2.CreateAccommodationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePriceInterval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_accommodation_search.AccommodationSearch/CreatePriceInterval',
            accommodation__search__pb2.CreatePriceIntervalRequest.SerializeToString,
            accommodation__search__pb2.CreatePriceIntervalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_accommodation_search.AccommodationSearch/CreateReservation',
            accommodation__search__pb2.CreateReservationRequest.SerializeToString,
            accommodation__search__pb2.CreateReservationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_accommodation_search.AccommodationSearch/DeleteReservation',
            accommodation__search__pb2.DeleteReservationRequest.SerializeToString,
            accommodation__search__pb2.DeleteReservationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteHostsAccommodations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_accommodation_search.AccommodationSearch/DeleteHostsAccommodations',
            accommodation__search__pb2.DeleteHostsAccommodationsRequest.SerializeToString,
            accommodation__search__pb2.DeleteHostsAccommodationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
