# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: accommodation-search.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61\x63\x63ommodation-search.proto\x12\x19grpc_accommodation_search\"\xda\x02\n\x10\x41\x63\x63ommodationDTO\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06hostId\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x11\n\tminGuests\x18\x05 \x01(\x05\x12\x11\n\tmaxGuests\x18\x06 \x01(\x05\x12\x17\n\x0fweekendIncrease\x18\x07 \x01(\x05\x12\x34\n\x08location\x18\x08 \x01(\x0b\x32\".grpc_accommodation_search.Address\x12\r\n\x05photo\x18\t \x01(\t\x12\x37\n\tpriceType\x18\n \x01(\x0e\x32$.grpc_accommodation_search.PriceType\x12\x34\n\x08\x62\x65nefits\x18\x0b \x03(\x0b\x32\".grpc_accommodation_search.Benefit\x12\x14\n\x0cgeneralPrice\x18\x0c \x01(\x02\"#\n\x07\x42\x65nefit\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"H\n\x07\x41\x64\x64ress\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x0e\n\x06street\x18\x03 \x01(\t\x12\x0e\n\x06number\x18\x04 \x01(\t\"\x1d\n\x1b\x43reateAccommodationResponse*(\n\tPriceType\x12\r\n\tPER_GUEST\x10\x00\x12\x0c\n\x08IN_WHOLE\x10\x01\x32\x91\x01\n\x13\x41\x63\x63ommodationSearch\x12z\n\x13\x43reateAccommodation\x12+.grpc_accommodation_search.AccommodationDTO\x1a\x36.grpc_accommodation_search.CreateAccommodationResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'accommodation_search_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRICETYPE._serialized_start=548
  _PRICETYPE._serialized_end=588
  _ACCOMMODATIONDTO._serialized_start=58
  _ACCOMMODATIONDTO._serialized_end=404
  _BENEFIT._serialized_start=406
  _BENEFIT._serialized_end=441
  _ADDRESS._serialized_start=443
  _ADDRESS._serialized_end=515
  _CREATEACCOMMODATIONRESPONSE._serialized_start=517
  _CREATEACCOMMODATIONRESPONSE._serialized_end=546
  _ACCOMMODATIONSEARCH._serialized_start=591
  _ACCOMMODATIONSEARCH._serialized_end=736
# @@protoc_insertion_point(module_scope)
