# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import accommodation_search_pb2 as accommodation__search__pb2


class AccommodationSearchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAccommodation = channel.unary_unary(
                '/grpc_accommodation_search.AccommodationSearch/CreateAccommodation',
                request_serializer=accommodation__search__pb2.AccommodationDTO.SerializeToString,
                response_deserializer=accommodation__search__pb2.CreateAccommodationResponse.FromString,
                )


class AccommodationSearchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAccommodation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccommodationSearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAccommodation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccommodation,
                    request_deserializer=accommodation__search__pb2.AccommodationDTO.FromString,
                    response_serializer=accommodation__search__pb2.CreateAccommodationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_accommodation_search.AccommodationSearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AccommodationSearch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAccommodation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_accommodation_search.AccommodationSearch/CreateAccommodation',
            accommodation__search__pb2.AccommodationDTO.SerializeToString,
            accommodation__search__pb2.CreateAccommodationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
