  # my global config
  global:
    scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
    evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
    # scrape_timeout is set to the global default (10s).

  # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
  rule_files:
   - "rules/recording_rules.yml"

  scrape_configs:
    - job_name: 'prometheus'

      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.

      static_configs:
        - targets: ['localhost:9090']

    - job_name: 'web.bff'
      metrics_path: '/metrics'
      static_configs:
        - targets: ['web.bff:80']

    - job_name: 'identity.api'
      metrics_path: '/metrics'
      static_configs:
        - targets: ['identity.api:80']

    - job_name: 'reservations.api'
      metrics_path: '/metrics'
      static_configs:
        - targets: ['reservations.api:80']

    - job_name: 'search.api'
      metrics_path: '/metrics'
      static_configs:
        - targets: ['search.api:80']

    - job_name: 'notifications.signalr'
      metrics_path: '/metrics'
      static_configs:
        - targets: ['notifications.signalr:80']

    - job_name: 'ratings.api'
      metrics_path: '/metrics'
      static_configs:
        - targets: ['ratings.api:80']

    - job_name: 'recommendationsystem.api'
      metrics_path: '/metrics'
      static_configs:
        - targets: ['recommendationsystem.api:80']

    - job_name: 'node_exporter'
      static_configs:
        - targets: [ 'node-exporter:9100' ]

    - job_name: 'cAdvisor'
      static_configs:
        - targets: [ 'cadvisor:8080' ]
