version: '3.4'

services:
  web.bff:
    image: ${DOCKER_REGISTRY-}webbff
    build:
      context: .
      dockerfile: src/ApiGateway/Web.Bff/Dockerfile
    ports:
     - 10000:80

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
    ports:
    - 11000:80

  identity.db:
    image: postgres:alpine
    restart: always
    environment:
     POSTGRES_USERNAME: postgres
     POSTGRES_PASSWORD: 123456
    volumes:
     - identity-data:/var/lib/postgresql/data
    ports:
     - 21000:5432

  reservations.api:
    image: ${DOCKER_REGISTRY-}reservationsapi
    build:
      context: .
      dockerfile: src/Services/Reservations/Reservations.API/Dockerfile
    ports:
     - 12000:80

  reservations.db:
    image: postgres:alpine
    restart: always
    environment:
     POSTGRES_USERNAME: postgres
     POSTGRES_PASSWORD: 123456
    volumes:
     - reservations-data:/var/lib/postgresql/data
    ports:
     - 22000:5432

volumes:
  identity-data:
  reservations-data:


