version: '3.4'

services:
  flightbooking.api:
    image: ${DOCKER_REGISTRY-}flightbookingapi
    build:
      context: .
      dockerfile: src/FlightBooking.API/Dockerfile  
    ports:
     - 50000:80

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - 27000:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always

volumes:
  mongo_data:
